apiVersion: v1
data:
  # datxadmin / eddde262-b4a5-4a20-8bdb-3b7f0984c836
  auth: ZGF0eGFkbWluOiRhcHIxJDRGTWpUT0lWJGNvNS5ILkNzUDVpbXExQnVwYW4xOTE=
kind: Secret
metadata:
  name: basic-auth
  namespace: longhorn-system
type: Opaque
