apiVersion: v1
data:
  auth: datxadmin:$apr1$4FMjTOIV$co5.H.CsP5imq1Bupan191 # datxadmin / eddde262-b4a5-4a20-8bdb-3b7f0984c836
kind: Secret
metadata:
  name: basic-auth
  namespace: longhorn-system
type: Opaque
