all:
  hosts:
    hc-k8s-dev01-master01:
      ansible_host: 10.32.192.11
      ip: 10.32.192.11
      access_ip: 10.32.192.11
    hc-k8s-dev01-master02:
      ansible_host: 10.32.192.12
      ip: 10.32.192.12
      access_ip: 10.32.192.12
    hc-k8s-dev01-master03:
      ansible_host: 10.32.192.13
      ip: 10.32.192.13
      access_ip: 10.32.192.13
    hc-k8s-dev01-worker01:
      ansible_host: 10.32.192.21
      ip: 10.32.192.21
      access_ip: 10.32.192.21
    hc-k8s-dev01-worker02:
      ansible_host: 10.32.192.22
      ip: 10.32.192.22
      access_ip: 10.32.192.22
    hc-k8s-dev01-worker03:
      ansible_host: 10.32.192.23
      ip: 10.32.192.23
      access_ip: 10.32.192.23
    hc-k8s-dev01-worker04:
      ansible_host: 10.32.192.24
      ip: 10.32.192.24
      access_ip: 10.32.192.24
    hc-k8s-dev01-worker05:
      ansible_host: 10.32.192.25
      ip: 10.32.192.25
      access_ip: 10.32.192.25
  children:
    kube_control_plane:
      hosts:
        hc-k8s-dev01-master01:
        hc-k8s-dev01-master02:
        hc-k8s-dev01-master03:
    kube_node:
      hosts:
        hc-k8s-dev01-worker01:
        hc-k8s-dev01-worker02:
        hc-k8s-dev01-worker03:
        hc-k8s-dev01-worker04:
        hc-k8s-dev01-worker05:
    etcd:
      hosts:
        hc-k8s-dev01-master01:
        hc-k8s-dev01-master02:
        hc-k8s-dev01-master03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
